cone: cone.c
	gcc cone.c -o cone

sphere: sphere.c
	gcc sphere.c -o sphere

notes: notes.c
	gcc notes.c -o notes

multipleOfFive: multipleOfFive.c
	gcc multipleOfFive.c -o multipleOfFive

squareInCircle: squareInCircle.c
	gcc squareInCircle.c -o squareInCircle

imaginary: imaginary.c
	gcc imaginary.c -o imaginary